FROM python:3.9-slim

WORKDIR /code

COPY requirements.txt .

RUN pip install --upgrade pip

# packages that we need
RUN pip install cython && \
    pip install numpy && \
    pip install pandas && \
    pip install tweepy && \
    pip install pandas_ods_reader

    
